name: Test ESP32 Application

on:
  workflow_dispatch:
    inputs:
      prefix:
        description: 'Prefix for binary name'
        required: true
        default: 'snow'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: [esp-box-3, esp32_p4_function_ev_board]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build-example.yml
          name: ${{ github.event.inputs.prefix }}-${{ matrix.board }}.bin
          path: build.${{ matrix.board }}

      - name: Use Wokwi CI Server
        uses: wokwi/wokwi-ci-server-action@v1

      - name: Simulate & take a screenshot
        run: |
          curl -L https://wokwi.com/ci/install.sh | sh
          /home/runner/.wokwi/bin/wokwi-cli \
            --timeout 10000 \
            --timeout-exit-code 0 \
            --screenshot-part "esp" \
            --screenshot-time 12000 \
            --elf "build.${{ matrix.board }}/${{ github.event.inputs.prefix }}-${{ matrix.board }}.bin" \
            --fail-text 'Rebooting...' \
            --screenshot-file "screenshot-${{ matrix.board }}.png" \
            --serial-log-file 'wokwi-logs-${{ matrix.board }}.txt' \
            "examples/snow/boards/${{ matrix.board }}"
        # Following option is not used in this case, because we need to wait for screenshot
        # --expect-text 'Entering main loop...'
        env:
          WOKWI_CLI_TOKEN: ${{ secrets.WOKWI_CLI_TOKEN }}

    #   - name: Run tests using Wokwi CLI
    #     uses: wokwi/wokwi-ci-action@v1
    #     with:
    #       token: ${{ secrets.WOKWI_CLI_TOKEN }}
    #       path: boards/${{ matrix.board }}
    #       elf: build.${{ matrix.board }}/${{ github.event.inputs.prefix }}-${{ matrix.board }}.bin
    #       timeout: 20000
    #       expect_text: 'Entering main loop...'
    #       fail_text: 'Rebooting...'
    #       serial_log_file: 'wokwi-logs-${{ matrix.board }}.txt'

    #   - name: Upload Wokwi Logs
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: wokwi-logs-${{ matrix.board }}
    #       path: wokwi-logs-${{ matrix.board }}.txt

      - name: Upload Screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-${{ matrix.board }}
          path: screenshot-${{ matrix.board }}.png
