name: Upload SDL Component to Espressif Component Registry

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Component Version (leave empty to use version from idf_component.yml)'
        required: false
        type: string
  push:
    tags:
      - 'v*'
  release:
    types: [published]

jobs:
  upload_component:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          
      - name: Set version from various sources
        id: set_version
        run: |
          # Read version from idf_component.yml as the primary source
          YML_VERSION=$(grep '^version:' sdl/idf_component.yml | awk '{print $2}')

          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            # Use git tag version if available
            VERSION=${GITHUB_REF#refs/tags/v}
            echo "Using version from git tag: $VERSION"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ github.event.inputs.version }}" ]]; then
            # Use manual input version if provided
            VERSION="${{ github.event.inputs.version }}"
            echo "Using version from manual input: $VERSION"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            # Use version from idf_component.yml as default
            echo "Using version from idf_component.yml: $YML_VERSION"
            echo "version=$YML_VERSION" >> $GITHUB_OUTPUT
          fi

      - name: Update component version in yml if needed
        run: |
          CURRENT_VERSION=$(grep '^version:' sdl/idf_component.yml | awk '{print $2}')
          TARGET_VERSION="${{ steps.set_version.outputs.version }}"
          
          if [[ "$CURRENT_VERSION" != "$TARGET_VERSION" ]]; then
            echo "Updating version from $CURRENT_VERSION to $TARGET_VERSION"
            sed -i "s/^version:.*/version: $TARGET_VERSION/" sdl/idf_component.yml
          else
            echo "Version already matches: $TARGET_VERSION"
          fi
          
      - name: Display component info
        run: |
          echo "Component: sdl"
          echo "Namespace: georgik"  
          echo "Version: ${{ steps.set_version.outputs.version }}"
          echo "Repository: https://github.com/georgik/esp-idf-component-SDL"
          echo "---"
          cat sdl/idf_component.yml
          
      - name: Upload SDL component to ESP Component Registry
        uses: espressif/upload-components-ci-action@v1
        with:
          name: "sdl"
          namespace: "georgik"
          directories: "sdl"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
          
      - name: Upload success notification
        if: success()
        run: |
          echo "✅ Successfully uploaded SDL v${{ steps.set_version.outputs.version }} to ESP Component Registry!"
          echo "🔗 Available at: https://components.espressif.com/components/georgik/sdl"
          echo "📋 Examples available via: idf.py create-project-from-example 'georgik/sdl=${{ steps.set_version.outputs.version }}:snow'"
          
      - name: Upload failure notification  
        if: failure()
        run: |
          echo "❌ Failed to upload SDL v${{ steps.set_version.outputs.version }} to ESP Component Registry"
          echo "Please check the logs above for details"
