name: Upload components to Espressif Component Service

on:
  workflow_dispatch:
    inputs:
      board:
        description: 'Version'
        required: true
        default: '1'

jobs:
    upload_components:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
            with:
              submodules: "recursive"
          - name: Upload component to the component registry
            uses: espressif/upload-components-ci-action@v1
            with:
              name: "sdl"
              namespace: "georgik"
              api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
